name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - LICENSE.md
      - README.md

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/environments/shared
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.6
    - name: Initialize
      run: terraform init -backend=false
    - name: Format
      run: terraform fmt -check -recursive
    - name: Validate
      run: terraform validate

  caller-identity:
    name: Check caller identity
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github
    - run: aws sts get-caller-identity
